### PR TITLE
UF-227 - Shrinking browser window creates scrollbars

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by romartin** [comment]
Hey Cristiano,
I tested the fix in my local with both Dashbuilder and KIE WB and works fine :) Great!
If you want me to merge the PR np, just let me know.
Thanks!

**Comment by csadilek** [comment]
Thanks, @cristianonicolai!
 
master: edb500cb84e630b486db01773f47c64c64df4025
0.7.x: 7827290a3f6d982fa59a6b140eaca34136e484a4

When testing this, I found that it now revealed an issue when the project explorer is being resized which we'll fix independently in uberfire-extensions.

**Comment by romartin** [comment]
Thanks guys!

**Comment by cristianonicolai** [comment]
great! thanks @romartin and @csadilek

**Pull request closed without merging**
