### PR TITLE
Upgrade wildfly-dist to 10.0.0.Final.

### PR DESCRIPTION
**Pull request by psiroky**
* refactored the wildfly version property
   into uf-parent for better reusability

### CODE REVIEW

**Comment by csadilek** [comment]
Needs https://github.com/errai/errai/pull/176 to be merged first. The test failure is also related, unfortunately. I can look into that in a bit. //cc @mbarkley @psiroky

**Comment by mbarkley** [comment]
@psiroky @csadilek 

It looks like the problem is caused by a bug in the wildfly-domain-management artifact for the new version (2.1.0.Final). You can see the problematic code [here](https://github.com/wildfly/wildfly-core/blob/2.1.0.Final/domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesFileLoader.java#L230-L238).

The failing test tries to delete a user. But when this persistProperties method is called, it still writes the line with the deleted user to the properties file in the else block. It looks like this problem exists in all the newer versions (2.2.0.CR2 and 3.0.0.Alpha1) as well.

I can send them a PR to fix this later today, but how will we proceed in the interim?

**Comment by csadilek** [comment]
@psiroky we have a fix for this on my fork (amended your commit): https://github.com/csadilek/uberfire/commit/d5614f784f925faabad57286dd04cd81af34e894

Can you replace your commit with this one and update this PR? This is a temporary solution until the WF bug is fixed, but it's not worth waiting for that at this point.

**Comment by psiroky** [comment]
@csadilek, @manstis  thanks guys, I will update the PR shortly.

**Comment by manstis** [comment]
@psiroky I take no credit.. thank @mbarkley :)

**Comment by psiroky** [comment]
@manstis right, sorry @mbarkley :) the thanks should really go to you

**Comment by csadilek** [comment]
+1

**Pull request merged**
