### PR TITLE
GWTBoostrap Widgets are not working in layout editor preview due to unattached gwt widgets

### PR DESCRIPTION
**Pull request by ederign**
screen shot 2017-01-12 at 5 49 34 pm

### CODE REVIEW

**Comment by ederign** [comment]
@pefernan could you please try and see if it fix your issue?

**Comment by manstis** [comment]
IDK if this explains things https://issues.jboss.org/browse/ERRAI-936 (but not a solution!)

**Comment by ederign** [comment]
@manstis this is related. GWT widgets are not attached when u added then dynamically to a @Templated, preventing the correct initialization. 
Using DOMUtil.appendWidgetToElement( div, gwtDivWrapper ) attach them and fix the issue (hopefully).

**Comment by mbarkley** [comment]
+1

**Comment by pefernan** [comment]
+1

**Pull request merged**
