### PR TITLE
RHBPMS-473: Set TCCL to workaround login failures with JSM enabled

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by porcelli** [comment]
jenkins please retest

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
@porcelli I've amended your commit with a test to cover this change here: https://github.com/csadilek/uberfire/commit/b1d1e12922bd94677dff7c7a0b6643ae7afb3f41

Maybe you want to bring it in.

**Comment by porcelli** [comment]
jenkins retest this

**Pull request merged**
