### PR TITLE
BZ-1278227: enable ssh idle timeout to be configurable

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by porcelli** [comment]
0.6.x was sorta dead.. just pushed just in case

**Comment by manstis** [comment]
ok to test (sorry, I forget what I'm meant to ask)

**Comment by manstis** [comment]
@csadilek @porcelli If we agree, since 0.6.x is as good as dead, we don't need tests I can +

**Comment by csadilek** [comment]
@manstis @porcelli's PR on master has the tests. don't think we need to backport the tests here.

**Comment by csadilek** [comment]
https://github.com/uberfire/uberfire/pull/241

**Comment by porcelli** [comment]
0.6.x for sure is dead

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Test failures not related to this change.

**Comment by csadilek** [comment]
0.6.x: ec535ad644ea8c0ce1fb54836bee9b7a0deb6c0b

**Pull request closed without merging**
