### PR TITLE
GUVNOR-2553: Guided Decision Table Editor: Fix exit 'pinned mode' when closing a document

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2553

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by ederign** [comment]
+1 thanks @manstis

**Pull request merged**
