### PR TITLE
upgraded jboss-ip-bom

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by psiroky** [comment]
The build failed because the ip-bom-6.0.2.Final is not yet synced into Maven central (can take up to one day after releasing). So we either need to wait of add the repository.jboss.org into the pom.xml (like it is already done in other repos).

**Comment by psiroky** [comment]
I've re-triggered the build. Once it succeeds I will merge.

**Comment by psiroky** [comment]
Merged into 0.8.x

**Pull request closed without merging**
