### PR TITLE
BZ-1265604, BZ-1266138: fixes issues related to lifecycle management of

### PR DESCRIPTION
**Pull request by porcelli**
beans (priority disposable). Due the nature of WAS CDI implementation,
had to initialize clustering outside ServletContextListener.

### CODE REVIEW

**Comment by manstis** [comment]
Looks ok other than missing licenses :-(

Your comparator to sort PriorityDisposables is overly complicated but does the same.

**Comment by porcelli** [comment]
@manstis licenses will be all (codebase) updated in a upcoming PR ;)

**Comment by porcelli** [comment]
@manstis maybe my comparator is too much... but iirc in theory it's right (in a sense it uses 0) :P

**Comment by manstis** [comment]
Other than missing licenses; +1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: 1c825f54d2970e2da96c8d52aeafdbbc950d2414

**Pull request closed without merging**
