### PR TITLE
Properly depend on freemarker + fix compiler args

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by ederign** [comment]
@psiroky did you try this on eclipse? Because on the old commit message, jfuerth did this in order to fix a Eclipse issue. We need to make sure that uberfire still works in eclipse env.

**Comment by psiroky** [comment]
@ederign I did not. Using shading to fix some Eclipse issue is just horrible. I'll try to open the project in eclipse to see what happens.

**Comment by psiroky** [comment]
I am not an Eclipse user, so not sure what to look for (and the old commit message does not say either). The project opens fine and I can execute tests in `uberfire-workbench-processors-tests` module.

**Comment by ederign** [comment]
+1 thanks @psiroky

**Pull request merged**
