### PR TITLE
Allow modal footer to be customized

### PR DESCRIPTION
**Pull request by cristianonicolai**
Only add default footer in case a container using modal-footer class isn't provided

### CODE REVIEW

**Comment by manstis** [comment]
How, where, why does this compare to BaseModal IIRC we had floating around somewhere and used as the Base for all (most) popup in (at least) KIE Workbench etc?

**Comment by cristianonicolai** [comment]
@manstis true, most cases use BaseModal AFAIK. Problem is that I found some cases ( ex: ServerRegistryEndpointPresenter, ProcessInstanceSignalPresenter ) where @WorkbenchPopup still in use and this screens have duplicated action buttons. The ones defined in the pop-up plus the default OK one. This is the simplest fix I could think of without a major refactor to use BaseModal.

**Comment by manstis** [comment]
@cristianonicolai OK, to be honest I cannot see why the *old* code did not work correctly; but that said your new code does much the same thing in a round about way and, if it fixes the issue, then +1 to merge!

**Comment by csadilek** [comment]
master: 31d658d4ff1c1ed35285687095f7d8922987456b

**Pull request closed without merging**
