### PR TITLE
GUVNOR-2807: File Explorer in Admin view freezes when a project is extended

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2807

New methods to facilitate Unit Testing.

### CODE REVIEW

**Comment by manstis** [comment]
Fix for JIRA is here: https://github.com/droolsjbpm/guvnor/pull/397

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
+1

**Pull request merged**
