### PR TITLE
BPMSPL-301: request to improve error message while uploading spreadsheet with multibyte name

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/BPMSPL-301

### CODE REVIEW

**Comment by ederign** [comment]
@manstis could you please take a look on this?

**Comment by manstis** [comment]
+1 to merge (with related https://github.com/droolsjbpm/drools-wb/pull/240)

**Comment by manstis** [comment]
@ederign The ```drools-wb``` PRs are not dependent upon these.. they can be merged whenever you like.

**Comment by ederign** [comment]
Thanks @karreiro

**Comment by karreiro** [comment]
You're welcome @ederign :D I think that this [PR](https://github.com/uberfire/uberfire-extensions/pull/281) could be merged too.

**Pull request merged**
