### PR TITLE
UF-185: Panel Height Lost when goTo(placeRequest, panel)

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
Depends on: https://github.com/uberfire/uberfire-extensions/pull/248

**Comment by paulovmr** [comment]
This PR also fixes the issue [UF-285](https://issues.jboss.org/browse/UF-285).

**Comment by porcelli** [comment]
it looks good, but this is a change that to be sure it's necessary to run to see.

**Comment by ederign** [comment]
@porcelli @paulovmr I'll try this locally!

**Comment by ederign** [comment]
+1 thanks @paulovmr

**Comment by csadilek** [comment]
master: be001e52c1a364b684463c4651951a86e5a5744b

**Pull request closed without merging**
