### PR TITLE
RHBPMS-473: Set TCCL to workaround login failures with JSM enabled

### PR DESCRIPTION
**Pull request by martinweiler**

### CODE REVIEW

**Comment by karreiro** [comment]
@porcelli @martinweiler I just tested the PR on WAS and everything works fine. However, I’m not able to test it with JSM enabled.

**Comment by porcelli** [comment]
jenkins please retest this

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by porcelli** [comment]
Code has been updated, new PR has been submited (#608)

**Pull request closed without merging**
