### PR TITLE
UF-456: Rename .gitignore file created in empty directory to .gitkeep

### PR DESCRIPTION
**Pull request by mcimbora**
Rename .gitignore to .gitkeep to describe the purpose of the file in a better way.

### CODE REVIEW

**Comment by psiroky** [comment]
Why do we need to keep empty directories? (You've probably covered this in the IRC discussion, but I missed that one)

**Comment by mcimbora** [comment]
@psiroky I believe this is necessary in order to create a new package (with no content) inside the workbench.

**Comment by psiroky** [comment]
@mcimbora ah, right, makes sense - thanks!

**Comment by mcimbora** [comment]
Failed test is unrelated


```
Error Message

Unexpected exception, expected<org.uberfire.ext.security.management.api.exception.GroupNotFoundException> but was<org.uberfire.ext.security.management.api.exception.SecurityManagementException>

Stacktrace

java.lang.Exception: Unexpected exception, expected<org.uberfire.ext.security.management.api.exception.GroupNotFoundException> but was<org.uberfire.ext.security.management.api.exception.SecurityManagementException>
	at org.uberfire.ext.security.management.wildfly.properties.WildflyGroupsPropertiesManagerTest.testDeleteGroup(WildflyGroupsPropertiesManagerTest.java:156)
Caused by: java.util.ConcurrentModificationException
	at org.uberfire.ext.security.management.wildfly.properties.WildflyGroupsPropertiesManagerTest.testDeleteGroup(WildflyGroupsPropertiesManagerTest.java:156)
```

**Comment by ederign** [comment]
jenkins retest this

**Comment by mcimbora** [comment]
@ederign This failure is not related as well. Should I create new issues for the random failures? Tried running the testsuite locally without issues.

{code}
Inner after batch
Inner after write
Inner after close
[main] ERROR org.uberfire.java.nio.fs.jgit.util.JGitUtil - Unexpected exception (1/0).
Inner after end batch
java.io.FileNotFoundException: /home/jenkins/workspace/uberfire-pullrequests/uberfire-io/target/temp514726912861386240184978037433/.niogit/amend-repo-test.git/refs/heads/master (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.jgit.util.IO.readSome(IO.java:101)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.scanRef(RefDirectory.java:950)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.readRef(RefDirectory.java:920)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.getRef(RefDirectory.java:295)
	at org.eclipse.jgit.lib.Repository.resolveSimple(Repository.java:787)
	at org.eclipse.jgit.lib.Repository.parseSimple(Repository.java:777)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:489)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:435)
	at org.uberfire.java.nio.fs.jgit.util.JGitUtil.lambda$checkPath$8(JGitUtil.java:1371)
	at org.uberfire.java.nio.fs.jgit.util.JGitUtil.retryIfNeeded(JGitUtil.java:815)
	at org.uberfire.java.nio.fs.jgit.util.JGitUtil.checkPath(JGitUtil.java:1368)
	at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.deleteAssetIfExists(JGitFileSystemProvider.java:1408)
	at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.deleteIfExists(JGitFileSystemProvider.java:1386)
	at org.uberfire.java.nio.base.dotfiles.DotFileUtils.buildDotFile(DotFileUtils.java:65)
	at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider$4.close(JGitFileSystemProvider.java:1099)
	at org.uberfire.io.impl.AbstractIOService.write(AbstractIOService.java:639)
	at org.uberfire.io.impl.AbstractIOService.write(AbstractIOService.java:528)
	at org.uberfire.io.impl.AbstractIOService.write(AbstractIOService.java:536)
	at org.uberfire.io.impl.BatchTest.testTwoStartedFsOnBatchByTheSameThread(BatchTest.java:313)
{code}

**Comment by mcimbora** [comment]
Looks like the latter problem has been around for a while, e.g. in https://github.com/uberfire/uberfire/pull/594

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
@mcimbora they are not related but let's try to make it green on more time. There are already two jiras for this intermittent failure: UF-450 and UF-455

**Pull request merged**
