### PR TITLE
UF-275: Intellij git dir corrupted

### PR DESCRIPTION
**Pull request by ederign**
NoSuchElementException in JGitFileSystem should have a better error message

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks @ederign. I think it would be best (I know I am being picky) to also mention the -Dorg.uberfire.nio.git.dir setting directly in the error message in addition to the JIRA link.

Something like:

The gitnio directory is in an invalid state. If you are an IntelliJ IDEA user, there is a known bug which requires specifying a custom directory for your git repository. The gitnio directory is currently set to ... you can specify an alternative using -Dorg.uberfire.nio.git.dir (consider /tmp/abc). For more details please see https://issues.jboss.org/browse/UF-275.

**Comment by ederign** [comment]
@csadilek  msg updated.

**Comment by csadilek** [comment]
master: bbd17820e4fa573073a59a4d11b31538498d8f87

**Pull request closed without merging**
