### PR TITLE
RHBPMS-4220: Added RoleRegistry and registered principals that come from Keycloak remote logins as roles.

### PR DESCRIPTION
**Pull request by romartin**
Fixed issue that causing the security principals not being added as roles in the current user instance, so remote login (eg: keycloak) were failing due to authorizations failed, as users had no roles. In order to do this I've backported from master branch the RoleRegistry necessary stuff.

See https://issues.jboss.org/browse/RHBPMS-4220

Please @dgutierr, as commented with you this fix, can you please verify? Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
jenkins rebuild this ( got crazy with some signature check failed on an artifact... :)

**Comment by dgutierr** [comment]
Hi @Roger,

The implementation looks great!  

Aside from that, I think tests should be added for the JAASAuthenticacion and GroupAdapterAuthorizationSource classes in order to guarantee that the retrieval of groups & roles has proper coverage.

**Comment by romartin** [comment]
Hi @dgutierr , absolutely agree :) Added new commit with the tests for it! Added new commit with test as well for https://github.com/uberfire/uberfire-extensions/pull/301. Thanks!

**Comment by dgutierr** [comment]
@romartin I think the build is failing because in 0.9.x the new java 7+ nio api is not available, as it is on master. That explains why you get these errors in the log:

08:53:47 [ERROR] /home/jenkins/workspace/uberfire-pullrequests-0.9.x-and-older/uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/RoleLoader.java:76: Undefined reference: java.io.File java.nio.file.Path.toFile()
08:53:47 [ERROR] /home/jenkins/workspace/uberfire-pullrequests-0.9.x-and-older/uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/WebAppSettings.java:32: Undefined reference: java.nio.file.FileSystem java.nio.file.FileSystems.getDefault()
08:53:47 [ERROR] /home/jenkins/workspace/uberfire-pullrequests-0.9.x-and-older/uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/WebAppSettings.java:32: Undefined reference: String java.nio.file.FileSystem.getSeparator()
08:53:48 [ERROR] /home/jenkins/workspace/uberfire-pullrequests-0.9.x-and-older/uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/WebAppSettings.java:89: Undefined reference: java.nio.file.Path java.nio.file.Paths.get(String, String[])
08:53:48 [INFO]                                                                         

The solution is to use the legacy UF NIO api backport.

**Comment by psiroky** [comment]
@dgutierr, @romartin you should be able to reproduce the same fail when using the `full` profile (even when running with JDK 8). So something like `mvn clean install -Dfull` (which will add the `animal-sniffer` execution into the build)

**Comment by romartin** [comment]
ahh ok thanks for the update @psiroky !! I didnt realized about this, trying to fix now. Thanks!

**Comment by romartin** [comment]
Hi @dgutierr , @psiroky - thanks for the updates! 
Fixed the build issue and added a  commit again. Checked other dependant PRs as well after this fix. Hope jenkins will not complain now :)

**Comment by romartin** [comment]
yeahh passed :)

**Comment by csadilek** [comment]
+1

**Comment by manstis** [comment]
This appears to have broken tests in ```kie-wb-common``` and ```drools-wb```:-

https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-wb-pullrequests-6.x/101/testReport/junit/org.drools.workbench.jcr2vfsmigration/MortgagesRepoImportTest/testImportMortgagesRepo/
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common-pullrequests-6.x/165/testReport/org.kie.workbench.common.screens.explorer.backend.server/ExplorerServiceImplTest/explorerServiceShouldBeADependentBean/

**Comment by csadilek** [comment]
@manstis @romartin @dgutierr I will revert both commits involved.

**Comment by csadilek** [comment]
All three commits that is.

**Pull request merged**
