### PR TITLE
Tutorial fixes

### PR DESCRIPTION
**Pull request by hasys**
It is not possible to build demo project from official ubefire site if you going thought tutorial steps. There are possible fixes for this.

### CODE REVIEW

**Comment by ederign** [comment]
@hasys thanks for your contribution. Can you please squash the commits in just one?

**Comment by hasys** [comment]
@ederign thank you for fast reaction. Squashed.

**Comment by ederign** [comment]
thanks for your contribution @hasys.

After you finish the tutorial, if you have some comments on it drop an email or join #uberfire in freenode.

Also, if you want to contribute on something bigger for uf, just let me know.

**Comment by ederign** [comment]
+1.

**Pull request merged**
