### PR TITLE
[BZ#1202926] fix spaces in name of downloaded file

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by csadilek** [comment]
+1, @wmedvede this touches on one of your fixes, do you want to take a look? @jomarko I assume that would need a PR to 0.7.x as well?

**Comment by jomarko** [comment]
@csadilek you are right, there is the same problem on 0.7.x branch, I will create additional PR cherrypicking this commit.

**Comment by wmedvede** [comment]
+1  to merge
@jomarko also good simplification of the MockServletOutputStream

**Comment by jomarko** [comment]
@wmedvede , it was easy to simplify. Tests created by you were designed very well.

**Comment by csadilek** [comment]
Thanks!

master: af902a1fc45c25f63c1935f1bf0d267532cd391c

**Pull request closed without merging**
