### PR TITLE
Fix WorkbenchBackendEntryPointTest after log-level change

### PR DESCRIPTION
**Pull request by csadilek**
@porcelli @manstis fixing tests from previous commit (which I broke by changing the log level).

### CODE REVIEW

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
Jenkins retest this. (still the same intermittent (unrelated) failure)

**Pull request merged**
