### PR TITLE
[0.7.x] BZ1323878: [GSS] (6.2.z) AsyncWatchService dies when a RuntimeException is thrown from IOWatchServiceExecutorImpl.execute()

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1323878

(cherry picked from commit f70ef4c059d312db1fc07692fb845fd703f3f82b - BZ1323572)

This is the corollary of https://github.com/uberfire/uberfire/pull/343 for 0.7.x.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
The test is failing because Jenkins runs with JDK1.8 whereas the 0.7.x branch needs JDK<1.8.

If you merge this manually you can compile with JDK1.7 and the tests pass OK.

@psiroky I don't suppose there's much we can do re: changes to 0.7.x need JDK1.7?

**Comment by psiroky** [comment]
I can create different job for 0.7.x and 0.8.x which will use JDK 7 (similar as we have for kie repos). Will look at that this week.

**Comment by ederign** [comment]
+1

**Comment by ederign** [comment]
@manstis thanks

**Pull request merged**
