### PR TITLE
Upgrade IP BOM to 6.0.0.CR31; related build changes

### PR DESCRIPTION
**Pull request by psiroky**
* using ip-parent and ip-bom as uf-ext already uses those
 * moved build config moved directly into src/main/resources
   to avoid build issues for parallel builds
 * removed plugin versions already declared
   in ip-parent, jboss-parent

 * fixes few test failures related to jsoup upgrade

### CODE REVIEW

**Comment by psiroky** [comment]
We will probably need to wait till `jboss-integration-platform-parent:6.0.0.CR31` is synced into central, otherwise the build fails.

**Comment by psiroky** [comment]
Ready for review.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
Thanks.

master: a82c7624b43d6c1f67c921d722ce86c86eaeceef

**Pull request closed without merging**
