### PR TITLE
[0.7.x] BZ1299870: [GSS](6.2.x) Business Central Repo Clone Fails To Clone SCP Style SSH URLs

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1299870

This is the corollary of https://github.com/uberfire/uberfire/pull/298 for 0.7.x

NOTE 0.7.x has a different BZ number but the fix is the same.

(cherry picked from commit c0c1a8c224174822044e880b1d47fbfa0aa03aab)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@psiroky From what I can tell the ```java.io.IOException: invalid constant type: 18``` error is caused by something not being Java 8 (or 7) compatible. Is uberfire-0.7.x being compiled with Java 8? Should it be Java 1.6?

**Comment by manstis** [comment]
@psiroky I see [this](https://github.com/uberfire/uberfire/commit/60e30823d702e685e1525bb8ee848b1603da703d) on 0.8.x.. IDK whether I can apply the same to 0.7.x (I'm not confident about the other code changes made in the commit).

**Comment by psiroky** [comment]
Yeah, the 0.7.x build does not work with JDK 8 (and the PR job uses that). We will need to ignore it for now. I can take a look at this later (e.g. next week).

**Comment by manstis** [comment]
@psiroky More than happy to ignore - I know the failing test is nothing to do with my change!

**Comment by manstis** [comment]
@Rikkola Please note failing test is caused by CI configuration.. not the PR (I fixed 3 of the 4 failing tests by backporting a change made to 0.8.x, but the other failure relates to the PRs being built with Java 8 and not 1.6).... soooooooooooo, please feel free to +1 (or @porcelli if you find time!)

**Comment by Rikkola** [comment]
+1

**Pull request merged**
