### PR TITLE
Conditional place request equals and hashCode method should consider the resolved place request.

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by csadilek** [comment]
@paulovmr can you add some more details to the commit message please?

**Comment by csadilek** [comment]
+1. If @psiroky or @mbiarnes are around, I'd appreciate pointers to what's wrong with the jenkins PR builds (not triggering).

**Comment by csadilek** [comment]
@psiroky @mbiarnes re: jenkins. it seems for our current config (linux && mem16g) we only have a single node and it's stuck (rhel7-xlarge-3440).

**Comment by psiroky** [comment]
@csadilek I've restarted the Jenkins as one the plugins got stuck again. It should hopefully work now. If it's something more serious, I'll take a look on Monday.

**Pull request merged**
