### PR TITLE
upgraded to jboss-ip-bom 7.0.0.CR3

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by ederign** [comment]
@mbiarnes could you please check the conflicts?

**Comment by psiroky** [comment]
@mbiarnes this happened after merging #370. From now on we need to upgrade the ip-[bom|parent] version at the top-level module (used by parent) and inside uberfire-bom.

**Comment by mbiarnes** [comment]
@psiroky @ederign no merge conflicts anymore

**Comment by psiroky** [comment]
+1

**Comment by ederign** [comment]
thanks @mbiarnes

**Pull request merged**
