### PR TITLE
Cluster on WAS commits from 0.7x + adding testing coverage on it

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by ederign** [comment]
https://github.com/ederign/uberfire/commit/c5528fcc0c6478e00d7d83bdaa3d43e77fde1b0d  is the new commit.

**Comment by manstis** [comment]
I assume you're keeping the commits "unsquashed" to make matching with 0.7.x easier?

+1 to merge based upon my assumption.

**Comment by ederign** [comment]
@manstis exactly.

**Comment by csadilek** [comment]
Thanks!

master: 271e1d749bbab98be2c979ef9022e305a5a9c0c7 7348e26f9e42b7fadeec426a77aa1a90671acf8c 2525eb0c05e11ea706dc83b83f3d9e5d69574cd2 a0e66c8dbafd525204c03ebcb5842fd2e714203a

**Pull request closed without merging**
