### PR TITLE
Move DataGrid to uberfire-widgets-table (the only place directly usin…

### PR DESCRIPTION
**Pull request by mbarkley**
…g it).

This refactoring lets us remove the dependency on uberfire-workbench-client-views-patternfly
in uberfire-widgets-table.

### CODE REVIEW

**Comment by csadilek** [comment]
ok to test

**Comment by csadilek** [comment]
@mbarkley added you as a team member so your PRs don't have to be verified in the future.

**Comment by mbarkley** [comment]
@csadilek Thanks!

@ederign Please see my comment in [this PR](https://github.com/uberfire/uberfire-extensions/pull/273), explaining these changes.

**Comment by ederign** [comment]
@mbarkley thanks!

**Pull request merged**
