### PR TITLE
fix some exceptions and exception messages (mostly adding messages)

### PR DESCRIPTION
**Pull request by zkrejcov**
See also:
https://github.com/droolsjbpm/drools-wb/pull/162
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/26

### CODE REVIEW

**Comment by manstis** [comment]
@porcelli Could you please review?

**Comment by jhrcek** [comment]
Just a comment about these "exception message adding" commits to raise the awareness of the general problem we're sometimes facing.

Given that error handling in many backend service calls consists of only displaying the exception message in modal dialog (typical example is [here](https://github.com/droolsjbpm/jbpm-console-ng/blob/master/jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/tasklogs/TaskLogsPresenter.java#L98) or using [DefaultErrorCallback](https://github.com/uberfire/uberfire-extensions/blob/master/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/callbacks/DefaultErrorCallback.java) it is very important to use informative error messages to avoid situation when modal with message like "NullPointerException: null" is displayed and the exception (and stacktrace) is otherwise lost. This leads to difficulties when steps to reproduce the failure are not clear.

@porcelli @manstis Shoudln't we for example improve the DefaultErrorCallback so that the stacktrace is logged to browser javascript console or something so that we're not loosing valuable failure information? Or are there some other options  to handle this that I'm not aware of?

**Comment by manstis** [comment]
@jhrcek I'm not sure what value the callstack is in JS without "source maps" enabled (which is disabled in builds other than for SuperDevMode, i.e. development). I fear a callstack would be a hard-to-read string of obfuscated method calls. @csadilek Do you have any experience of this?

**Comment by zkrejcov** [comment]
@jhrcek +1 to informative exception messages, definitely. Actually to proper exception handling in general.. ;)

**Comment by csadilek** [comment]
@manstis @jhrcek If I understand the question correctly, symbol obfuscation isn't an issue here as this is about server-side exceptions (and details) getting serialized to the client. However, I would decide against this as you don't want to leak that level of server-side internals to the client. IMO, it's sufficient to provide a meaningful error message to the user and, at the same time, log the details (i.e. the stack trace) on the server. //cc @porcelli @zkrejcov

**Comment by manstis** [comment]
+1 to merge.

**Comment by porcelli** [comment]
just a comment, most of NIO2 backport should be removed as we're already on Java 8

**Pull request merged**
