### PR TITLE
added DSL release scripts

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by ederign** [comment]
jenkins retest this

**Comment by psiroky** [comment]
I can review this once I find some time...

**Comment by ederign** [comment]
@psiroky when you have time, can you please take a look on this?

**Comment by psiroky** [comment]
@ederign I can take a look, but not sure what is the current state. I commented similar PR for kie: https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/365. I guess we need to figure out how to proceed.

**Comment by mbiarnes** [comment]
@ederign @psiroky these script are helping to do the releases, Similar PRs for KIE and dashbuilder were merged. I want to merge these script before we branch uberfire to the next -SNAPSHOT version.

**Pull request merged**
