### PR TITLE
BZ1275325: WAS: indexing fails with ContextNotActiveException

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1275325

Implementation of EJB was flawed; it was neither an "no interface" bean, nor a "local interface" bean.

### CODE REVIEW

**Comment by psiroky** [comment]
Will this work on Tomcat, where there is no EJB implementation?

**Comment by manstis** [comment]
@psiroky Hi, I've not changed the underlying mechanism to create an Asynchronous Executor. We try to lookup a EJB Asynchronous Bean [here](https://github.com/manstis/uberfire/blob/BZ1275325/uberfire-commons/src/main/java/org/uberfire/commons/async/SimpleAsyncExecutorService.java#L65) if it fails - as it would on Tomcat - we fallback to our own thread pool [here](https://github.com/manstis/uberfire/blob/BZ1275325/uberfire-commons/src/main/java/org/uberfire/commons/async/SimpleAsyncExecutorService.java#L71).

**Comment by psiroky** [comment]
@manstis thanks for the explanation. I just saw "EJB" and immediately though about Tomcat....

**Comment by csadilek** [comment]
Thanks.

master: 064be4dcd4cb322341d160e01fb9f458d59c4175

**Comment by csadilek** [comment]
@jhrcek this is another good example where only an integration test would help guard against regressions on WAS. We have usage against the new interface in tests in kie-wb-common, but only an integration test can catch real problems here. Anyways, something for our list of ToDos.

**Pull request closed without merging**
