### PR TITLE
[from porcelli, leave here for now please] Git Squash operation

### PR DESCRIPTION
**Pull request by Salaboy**
Initial implementation for review.
@porcelli I didn't want to go deeper in the testing before checking the initial approach.

### CODE REVIEW

**Comment by ederign** [comment]
@Salaboy IMO, we should not create PR's just for initial implementations. 

That only creates noise and you can have this conversation sending a PR to @porcelli  forks.

**Comment by psiroky** [comment]
I agree with what @ederign. We should only create PRs against "blessed" repositories where the code is ready for review and merge.

**Comment by manstis** [comment]
I also agree with both Eden and Petr.

**Comment by Salaboy** [comment]
@ederign @psiroky @manstis I got the feeling that the issue was the word "initial" because the operation is complete and it is working. Do you see any other issue with the content of the PR? I think that the code is ready for review and merge, I was looking for that kind of feedback. I will avoid the word "initial" in my future PRs.

**Comment by psiroky** [comment]
@Salaboy Yes, you are right. For me the word "initial" looked like something that is not yet ready.

Also when mentioning "I didn't want to go deeper in the testing...", does that mean more tests are on the way?

**Comment by Salaboy** [comment]
@psiroky they will come in the future if they are needed, now the test provided check that the behaviour is the expected one

**Comment by csadilek** [comment]
@porcelli is this one good to go?

**Comment by porcelli** [comment]
@csadilek still on low priority, after BZs i'll be back to it

**Comment by ederign** [comment]
@porcelli do you still need this PR? I would like to keep this list clean! :)

**Comment by porcelli** [comment]
Yes, keep it there for now please

**Comment by porcelli** [comment]
@adrielparedes is working on it, and will submit a new PR soon. finally we can close this ;)

**Pull request closed without merging**
