### PR TITLE
UF-283: Upgrade uberfire-tutorial to Java 8 and Errai UI

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by ederign** [comment]
working on this.

**Comment by ederign** [comment]
@paulovmr ping when you make the changes ok?

**Comment by paulovmr** [comment]
@ederign All done!

**Comment by ederign** [comment]
+1 @thanks paulo (I've already tested locally)
Related PRs: 
https://github.com/uberfire/uberfire-tutorial/pull/7 
https://github.com/uberfire/uberfire-docs/pull/10

**Comment by csadilek** [comment]
master: 6053b550f4a16b0e0a89ad03d8143aaa2be6f7dc

**Pull request closed without merging**
