### PR TITLE
UF-305 - PatternFly upgrade to version 3.6.0

### PR DESCRIPTION
**Pull request by cristianonicolai**
Style fixes for upgrade
New theme GWT module

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@manstis @csadilek changes I mentioned regarding PatternFly, please have a look.
Please note that showcase apps need to be updated in the different repos to use the new GWT module: org.uberfire.client.views.PatternFlyTheme

**Comment by ederign** [comment]
Hi @cristianonicolai ! 

Why move PatternFly -> PatternFlyTheme ? And also, why keep both?

@csadilek @cristianonicolai @manstis do you guys have any plan in order to updgrade other showcases?

**Comment by csadilek** [comment]
+1

@ederign that was done to support different themes. The default community theme (PatternFlyBase->PatternFlyTheme) and a theme for the product (PatternFlyBase->KIETheme, based on rcue).

But, I am not sure why there are 3 modules ;) (PatternFlyBase, PatternFly and PatternFlyTheme).

@cristianonicolai can you clarify why there's an additional PatternFly.gwt.xml. Wouldn't it be enough to have PatternFlyBase->PatternFlyTheme and PatternFlyBase->KIETheme. In other words, why is KIETheme inheriting PatternFly which is then inheriting PatternFlyBase? Couldn't KIETheme directly inherit PatternFlyBase (like PatternFlyTheme does), esp. as PatternFly doesn't seem to add anything?

**Comment by csadilek** [comment]
@cristianonicolai to clarify would it be enough to have PatternFlyBase and PatternFlyTheme in UberFire?

Then have: 
KIETheme (product) inherit from PatternFlyBase, + rcue styles
KIETheme (community) inherit from PatternFlyTheme

**Comment by cristianonicolai** [comment]
@csadilek @ederign I agree, we have an extra module that we could remove from here. PatternFly module needs to stay basically to keep compatibility with all the GWT modules that inherits from it. Otherwise we would have to fix all of those just to rename from PatternFly to PatternFlyBase.
That way we would have:
KIETheme (product) inherit from PatternFly, + rcue styles
KIETheme (community) inherit from PatternFlyTheme
PatternFlyTheme inherit from PatternFly + patternfly styles
WDYT?

**Comment by csadilek** [comment]
@cristianonicolai ok, got it, thanks. I am fine either way.

**Comment by cristianonicolai** [comment]
@ederign I've pushed PRs for most webapps/showcases that I could find, hopefully I haven't missed any.

**Pull request merged**
