### PR TITLE
[DROOLS-2152] upgrade mockito, gwtmockito and powermockito to support JDK9

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by ederign** [comment]
Can you please move this PR for https://github.com/kiegroup/appformer ?

**Comment by psiroky** [comment]
@ederign I can. However, it will require a lot more changes to make this green and I won't have the time to fix all that. So unless someone else will take a look at that, it's probably unnecessary to move the PR at this point.

**Comment by ederign** [comment]
@porcelli ^

**Comment by psiroky** [comment]
I'll move the PR regardless so that we don't have to keep thinking about this repo.

**Comment by psiroky** [comment]
https://github.com/kiegroup/appformer/pull/102

**Pull request closed without merging**
