### PR TITLE
Upgrade IP BOM to 7.0.0.CR4 + related fixes

### PR DESCRIPTION
**Pull request by psiroky**
* fixes after JGit 3.x -> 4.x ugprade

 * minor updates related to JEE Spec upgrades

Depends on https://github.com/errai/errai/pull/180.

### CODE REVIEW

**Comment by psiroky** [comment]
All PRs mentioned in https://github.com/errai/errai/pull/180 need to be merged together, at the same time.

**Comment by csadilek** [comment]
+1

**Comment by ederign** [comment]
@psiroky last PR introduced some conflicts. could you please update it?

**Comment by psiroky** [comment]
Rebased, should be mergeable again.

**Comment by avkapustin** [comment]
Hello, could you also update JGit version in __ rootArtifactId __-parent-with-dependencies/pom.xml according to IP BOM?
Before 
```xml
<version.org.eclipse.jgit>3.7.1.201504261725-r</version.org.eclipse.jgit>
```
After
```xml
<version.org.eclipse.jgit>4.3.1.201605051710-r</version.org.eclipse.jgit>
```
Without it if generates project from archetype, exception was raised
```
Caused by: java.lang.NoSuchMethodError: org.eclipse.jgit.treewalk.TreeWalk.close()V
        at org.uberfire.java.nio.fs.jgit.util.JGitUtil.checkPath(JGitUtil.java:1278)
        at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.newOutputStream(JGitFileSystemProvider.java:819)
        at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.newFileSystem(JGitFileSystemProvider.java:712)
        at org.uberfire.java.nio.file.FileSystems.newFileSystem(FileSystems.java:117)
        at org.uberfire.java.nio.file.FileSystems.newFileSystem(FileSystems.java:83)
        at org.uberfire.io.impl.AbstractIOService.newFileSystem(AbstractIOService.java:244)
        at org.uberfire.backend.server.authz.AuthorizationPolicyVfsStorage.initFileSystem(AuthorizationPolicyVfsStorage.java:90)
        at org.uberfire.backend.server.authz.AuthorizationPolicyVfsStorage.init(AuthorizationPolicyVfsStorage.java:73)
```

**Comment by psiroky** [comment]
@avkapustin thanks for reporting this. I've created https://issues.jboss.org/browse/UF-339 with the aim to remove all the hardcoded version properties in archetypes and use maven filtering instead (to fix these kinds of issues once and for all).

**Pull request merged**
