### PR TITLE
GUVNOR-2559: Guided Decision Table Editor: Improve appearance (for Red Hat Summit)

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2559

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

https://github.com/uberfire/uberfire/pull/393
https://github.com/droolsjbpm/drools-wb/pull/201

**Comment by manstis** [comment]
Please do not merge.. just figuring something out...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola @csadilek @ederign <at>anyone.. could somebody please review?

It's 99% UI rendering changes, so don't expect a lot of tests..

**Comment by csadilek** [comment]
+1

**Pull request merged**
