### PR TITLE
RHBPMS-1725 : [ALL LANG] Unlocalized string 'Project Explorer' in Authoring -> Project Authoring.

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/RHBPMS-1725

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by ederign** [comment]
Thanks @Rikkola

**Comment by Rikkola** [comment]
Heh, I just did few easy tickets one day to keep sane. Had a few days when nothing worked so wanted to see something finished. So I should thank you for the ticket.

**Comment by Rikkola** [comment]
Just noticed. Nothing to see here! ;-)
Commenting on very old PRs. Confused what i18n issue I fixed and when.

**Pull request merged**
