### PR TITLE
Moving Social Activities Framework from kie-uberfire-extensions to uberfire-extensions

### PR DESCRIPTION
**Pull request by ederign**
The end of Kie-Uberfire-Extensions
==========================

This PR is the result of the extraction of Drools dependencies from social activities framework and his move to Uberfire Extensions.
The main objective is to reduce the number of repositories in our platform. After this PR, we should move/remove i18n-taglib and delete kie-uberfire-extensions repo. Changes:

uberfire
--------
* kie-uberfire-extensions become uberfire-extensions/uberfire-social-activities. There drools dependency implementation of SocialTimelineRulesQueryAPI was moved to guvnor;
* Added a social perspective to wires web app and also a fake implementation of SocialTimelineRulesQueryAPI just for widget testing purposes;

droolsjbpm-build-bootstrap
----------------------------
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/354: Removing kie-uberfire-social-activities from bom.

kie-uberfire-extensions
----------------------------
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/47 :  Deleting kie-uberfire-social-activities

guvnor
--------------

https://github.com/droolsjbpm/guvnor/pull/404 : Refactoring and adding the implementation of SocialTimelineRulesQuery https://github.com/ederign/guvnor/blob/de3a6bc107ba2ebf9df258311204a09311899408/guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/social/SocialTimelineRulesQuery.java.

kie-wb-common
-----------------
https://github.com/droolsjbpm/kie-wb-common/pull/633 : refactorings of deps and packages

jbpm-form modeler
-----------------
https://github.com/droolsjbpm/jbpm-form-modeler/pull/83 :  refactorings of deps and packages

drools-wb
-----------------
https://github.com/droolsjbpm/drools-wb/pull/380 :  refactorings of deps and packages
	
optaplanner-wb
-----------------
https://github.com/droolsjbpm/optaplanner-wb/pull/128 :  refactorings of deps and packages

kie-wb-distributions
-----------------
https://github.com/droolsjbpm/kie-wb-distributions/pull/436:  refactorings of deps and packages

### CODE REVIEW

**Comment by manstis** [comment]
@ederign Looks like you've removed the dependency on Drools (hence it was in ```kie-uberfire-extensions```) and introduced "fake" implementations of the classes that used to require Drools. What affect does this have on functionality. For example see ```SocialTimelineRulesQuery```.

**Comment by manstis** [comment]
@ederign OK.. I'll wait.. I see the other PRs coming.. and (assume) a Drools specific implementation of the interfaces may be in one of the other PRs (e.g. ```kie-wb-common``` or somewhere).

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this (I'll fix those tests in my next task)

**Comment by ederign** [comment]
Jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Pull request merged**
