### PR TITLE
add test for ValidationUtils

### PR DESCRIPTION
**Pull request by zkrejcov**
(part X of moving-tests-to-community series)

### CODE REVIEW

**Comment by yurloc** [comment]
Nice! I only miss one more positive example for "hidden" files, e.g. `.gitignore`.

**Comment by zkrejcov** [comment]
@yurloc afaik, those we actually do not allow and do not want to allow as valid filenames - I'm sure I could dig up some old Bugzilla for that...

**Comment by yurloc** [comment]
I see. If the purpose of the class is to validate user input only and if users are not allowed to create hidden files, then it makes sense.

**Comment by manstis** [comment]
+1 to merge.

Sweet test @zkrejcov :+1:

**Pull request merged**
