### PR TITLE
JBPM-5014 - OnResize needs to be called after animation finishes to a…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…llow correct width and height

### CODE REVIEW

**Comment by manstis** [comment]
Shouldn't the test verify onResize() *is* called - wasn't that the whole purpose of the change?

**Comment by cristianonicolai** [comment]
so the answer is yes and no :) The change makes sure that onResize() is only called after the animation is finished. I created two other checks that ensure onResize() is called when onComplete() callback is executed. Had to do a bit of refactor to allow the internal inner classes to be available for testing.

**Comment by manstis** [comment]
Thanks @cristianonicolai +1 to merge.

**Comment by csadilek** [comment]
0.8.x: 313653fe407d014d5e02be1a99f6fb7695ca9d7d

**Pull request closed without merging**
