### PR TITLE
UF-445 : Move UUID from uberfire-wires-core-api to uberfire-commons

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/UF-445

Depends on this:
https://github.com/droolsjbpm/drools-wb/pull/354

### CODE REVIEW

**Comment by manstis** [comment]
Do ```droolsjbpm``` repositories need any change following this (other than ```drools-wb``` to re-use this!)

**Comment by Rikkola** [comment]
Spent so much time in my local web worker branch that I forgot drools-wb already used this, but looks like that is the only one. Wires is just used by drools-wb, checked with Maven.

**Comment by ederign** [comment]
@Rikkola we are good to go? Or do we need a syncronized merge across other repos?

**Comment by ederign** [comment]
soooo @porcelli  ?

**Comment by ederign** [comment]
thanks @Rikkola

**Pull request merged**
