### PR TITLE
GUVNOR-2332 - Allow context menu to be displayed without selecting a …

### PR DESCRIPTION
**Pull request by cristianonicolai**
…menu item

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by ederign** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
Ready to merge/review once build succeeds.

@psiroky could you check the build error, it doesn't seems like related/side effect of my change.

**Comment by csadilek** [comment]
@cristianonicolai these are in fact failing tests caused by a recent Errai change. We'll take care of that. Not caused by this commit.

**Comment by psiroky** [comment]
I can't see how the fails could be caused by Jenkins. I can reproduce them locally and they have been failing for about 2 days on the master job. That being said, they definitely are not caused by your changes.

**Comment by csadilek** [comment]
Jenkins retest this.

**Comment by csadilek** [comment]
master: 1c14cbfd947da6f4dd8a76c062295186dee9b4b9

**Pull request closed without merging**
