### PR TITLE
changes in license header

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by csadilek** [comment]
@mbiarnes shouldn't we update all license headers in uberfire to "Red Hat, Inc. and/or its affiliates"? If so, that would be more that these 88 files.

**Comment by mbiarnes** [comment]
@csadilek got it - my reg exp that I applied in another repositories only found a fraction of what should be found. I will redo this.

**Comment by mbiarnes** [comment]
@csadilek please review this one - i hope this time everything is OK. there were 1118 files changed.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: e3cca8a61a532c47e6088d25fccc3ccd11623c84

**Pull request closed without merging**
