### PR TITLE
UF-334: upgrade of pfly to 3.5.0

### PR DESCRIPTION
**Pull request by porcelli**
c3/d3 added `manually` to showcase as this is the only place that this is used (dashbuilder uses different
tech).

### CODE REVIEW

**Comment by cristianonicolai** [comment]
+1

**Comment by porcelli** [comment]
@ederign @csadilek @manstis  can you please review?

**Comment by manstis** [comment]
@porcelli Looks OK to me; I'm a little uncertain about the location "where" unpacked resources end up; and the modified ```org.uberfire.UberfireShowcase/js/d3.min.js``` etc paths.. but if you've tried locally and it works OK then.... +1 from me.

**Comment by ederign** [comment]
building and trying this on kie-wb

**Comment by porcelli** [comment]
@csadilek ?

**Comment by csadilek** [comment]
+1

**Pull request merged**
