### PR TITLE
Remove 3rd party repositories

### PR DESCRIPTION
**Pull request by psiroky**
* all dependencies  should be available in Maven Central
   or JBoss Public repository. Tried with -Dfull and empty
   local maven repo and everything builds successfully.

 * We should not use any third party repos to ensure builds are reproducible, fast, etc. See https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/master/README.md#requirements-for-dependencies for more details.

### CODE REVIEW

**Comment by manstis** [comment]
Does it still compile with these repositories removed?

**Comment by psiroky** [comment]
Yes, tried with `-Dfull -Dmaven.repo.local=maven-repo` (the maven-repo dir was empty).

**Comment by manstis** [comment]
http://github.com/uberfire/uberfire/commit/297999768

**Comment by manstis** [comment]
Thanks Petr.

**Pull request closed without merging**
