### PR TITLE
UF-229: Configurable Workbench: Dynamic Screens are not properly displayed in Editor Screen on LayoutEditor

### PR DESCRIPTION
**Pull request by ederign**
- Also adds refactoring that introduces new Activity.getIdentifier() method

### CODE REVIEW

**Comment by ederign** [comment]
Please wait for @etirelli +1 before merge it.

**Comment by porcelli** [comment]
+1 as this is a cherry-pick from master.
still waiting @etirelli

**Comment by etirelli** [comment]
We will discuss this on Tuesday during the call. I will let you know after that if we merge for GA or for the update patch 1.

Thanks for preparing this @ederign

**Comment by porcelli** [comment]
@etirelli news?

**Comment by etirelli** [comment]
@porcelli @ederign the plan is to target this for 6.2.1 patch update, so ideally this should be merged only by the end of next week after the CR2/GA release is done.

**Comment by etirelli** [comment]
@porcelli @ederign this was discussed again during the PM call today, and the decision was reversed to include this in 6.2.0. 
@csadilek can you please merge this PR?

**Comment by manstis** [comment]
"Decision reversed to include in 6.2.0....please merge..." that's a little ambitious. I assume you mean "decision to exclude from 6.2.0 (include in 6.2.1)..." - if I was being picky ;-)

**Comment by etirelli** [comment]
:)

**Comment by csadilek** [comment]
0.7.x: 6a7c8561fbcbae31f43c7ba708c6c0d57dab52db

**Pull request closed without merging**
