### PR TITLE
BZ1275325: WAS: indexing fails with ContextNotActiveException

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1275325

Implementation of EJB was flawed; it was neither an "no interface" bean, nor a "local interface" bean.

### CODE REVIEW

**Comment by mswiderski** [comment]
just one comment we could add logger.debug into catch block here https://github.com/uberfire/uberfire/pull/204/files#diff-e9984cfa6dafef19bee2a91c5a06723cR67 to know the reason why it failed. As we might have some misconfiguration/library conflicts or so that will fail it on app servers while it should not be. Not a must to have but will simplify troubleshooting.

besides that looks good to me - +1

**Comment by manstis** [comment]
@mswiderski Logging added.

**Comment by mswiderski** [comment]
thank you

**Comment by csadilek** [comment]
Thanks.

0.7.x: 71edcdf4462489c8bb676d745baf80f8d52b982e

**Pull request closed without merging**
