### PR TITLE
Formatting uf code base with new code style: …

### PR DESCRIPTION
**Pull request by ederign**
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/tree/master/ide-configuration

@paulovmr @porcelli @psiroky @manstis what do you think about this? I'm tired of formatting issues.

### CODE REVIEW

**Comment by manstis** [comment]
Perhaps we should ask @hasys to review - who instigated the formatter changes in ```droolsjbpm```.... ;-)

**Comment by ederign** [comment]
@hasys could you please take also a look on this? At least to make sure that everything is ok?

**Comment by jhrcek** [comment]
@ederign @manstis the code style looks like what QE wants :) However before merging this, could you please consider merging Bob's PR https://github.com/uberfire/uberfire/pull/637 ? He's already resubmitted it because some previous changes made it un-mergeable and I figure merging this PR before his will make that un-mergeable again. I also think that reformatting the code in IDE AFTER his PR is merged is easier than to rebase his PR on top of this one..

**Comment by hasys** [comment]
Hi @ederign, @manstis,

from my side if you don't do formatting manually, but do it with KIE Group formatter it is OK. If you use another one it have to be present in repository. That's all I instigated :)

So changes looks good, thank you @ederign!

**Comment by ederign** [comment]
@jhrcek @manstis @hasys thanks for the review!

@jhrcek Bob's PR is still on discussions so I'll merge this.

**Pull request merged**
