### PR TITLE
BZ-1203696 - Access restrictions to assets does not work with custom rol...

### PR DESCRIPTION
**Pull request by mswiderski**
...es

### CODE REVIEW

**Comment by porcelli** [comment]
this is a quick and dirty fix... this has to be improved.

**Comment by mswiderski** [comment]
come on, it's not dirty it's just quick ;) + 1 needs to be improved

**Comment by porcelli** [comment]
@mswiderski so... tell me about a RoleDecisionManager type that uses Roles and groups... if not dirty... what could be? ;)

**Comment by mswiderski** [comment]
I usually call it "intermediate solution" but you have point with name suggests something else ;)

**Pull request merged**
