### PR TITLE
Upgrade to Errai 4.0.0-SNAPSHOT, GWT 2.8.0-beta1, and Java 8.

### PR DESCRIPTION
**Pull request by mbarkley**
* Fixes for ambiguous dependencies caused by new resolution
algorithm for concrete beans.
* Explicity enable alternatives.
* Update code using old bean manager API.
* Replace @TestMock with @Alternative

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 9cd9fa11f99c302fa94f16a03f8c84ed390ff470

**Comment by manstis** [comment]
New files lack license... otherwise seems ok to me.

**Comment by mbarkley** [comment]
@mantsis I will send a separate PR for this fix. Thanks for noticing that.

**Comment by qmx** [comment]
yay!

**Pull request closed without merging**
